repos:
  - repo: local
    hooks:
      - id: flutter-analyze
        name: Flutter analyze
        entry: flutter
        args: ["analyze"]
        language: system

  - repo: https://github.com/fluttercommunity/import_sorter
    rev: "f350497a11b1285c695595049e95a420068e7a9f"
    hooks:
      - id: flutter-import-sorter
        name: Import sorter
